name: Harmony Pipeline CD Trigger

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'LICENSE'
      - 'pull_request_template.md'
      - 'tsc/**'

jobs:
  call_workflow:
    uses: dwanim/.github/.github/workflows/Harmony_CICD.yml@master
    with:
      pipe_config: 'release'
      rez_config: 'rez-2'
